### ISSUE TITLE
A Small Software Design Bug

### ISSUE THREAD

**Issue by yytambaya** [Flutterwave/Node-v3#133]
Have you read our [Code of Conduct](https://github.com/Flutterwave/Python/blob/master/CONTRIBUTING.md)? By filing an Issue, you are expected to comply with it, including treating everyone with respect.

# Description

# Steps to Reproduce

1. 
2.  

## Reproduces how often

# Configuration
- API Version: 
- Environment: 
- Browser: 
- Language: 

# Additional Information

**Comment by corneliusyaovi** [comment]
There is no description for the issue. We'd be closing this out.

If you have any other issues, please raise another issue with the required information.
